name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # Configure permission to Docker
      - name: Configure Docker permissions
        run: sudo chown $USER /var/run/docker.sock

      # Verify Docker installation
      - name: Verify Docker installation
        run: docker --version
      
      # Run a Docker command to verify it works
      - name: Verify Docker access
        run: docker ps


      # Download and install Kubernetes Minikube
      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          rm minikube-linux-amd64

      # Start Minikube
      - name: Start Minikube
        run: minikube start

      # Install kubectl
      - name: Install kubectl
        run: sudo snap install kubectl --classic

      # Enable Ingress
      - name: Enable Ingress
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml

      # Apply Kubernetes deployment
      - name: Apply Kubernetes Deployment
        run: kubectl apply -f .

      # Get deployment
      - name: Get Deployment
        run: |
          curl cowsay.devopsharshit.wuaze.com

      - name: Add other actions
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
